apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: route-to-ingress
  name: route-to-ingress
  namespace: route-to-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-to-ingress
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: route-to-ingress
    spec:
      containers:
      - args:
        - --cluster-issuer=letsencrypt-production-http01
        image: ghcr.io/getupcloud/route-to-ingress:0.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER_DOMAIN
          value: ""
        - name: CLUSTER_ISSUER
          value: "letsencrypt-staging-http01"
        - name: DRY_RUN
          value: "true"
        - name: IGNORE_DANGEROUS_INGRESS_CLASS_NAME
          value: "false"
        - name: INGRESS_CLASS_NAME
          value: "route-to-ingress"
        - name: INGRESS_CONFIG_NAME
          value: "cluster"
        - name: NAMESPACE
          value: ""
        name: controller
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      serviceAccountName: route-to-ingress
      terminationGracePeriodSeconds: 10
